stages:          
  - build
  - deploy

build-job:      
  stage: build
  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  after_script:
    - docker image prune -a --force --filter "until=24h" # remove unused images to save some space

deploy_image:
  stage: deploy
  variables:
    GIT_DEPTH: 1 #only fetch 1 depth to speed this up, we don't need to pull 50 commits back
  script:
    # - curl -X POST $localHook
    - echo "redeployment sent"
